project:
  type: website

website:
  title: "Inside Rail"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tennis"
        href: tennis/index.qmd
      - text: "Racing"
        href: racing/index.qmd
      - text: "NFL"
        href: nfl/index.qmd
      - text: "Games"
        menu:
          - href: games/nl2/chapter1.qmd
            text: "NL2 â€” Chapter 1: The Call"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true